### ISSUE TITLE
Core application – auto complete should only search from the start of a word, not search for matches in middle of words

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#15]

**Comment by russgalloway** [comment]
Are you sure you want to change this behavior?  For new employees that aren't familiar with what things are called, searching by a "starts with" filter would be more difficult than a "contains" filter.

**Comment by ChongLi** [comment]
can we limit results from showing until there are 3 or more characters typed in?  I think the users see the problem with currently functionality is mainly due to all the irrelevant results coming back when a single letter is typed in when starting to type the search.  limiting results until a few characters are typed in may help

**Comment by j-hogue** [comment]
We can do that.

**Comment by j-hogue** [comment]
Completed
